name: ✨ Feature request
description: Suggest an idea for this project
title: "[FEATURE] "
labels:
    - enhancement

body:
    - type: markdown
      attributes:
          value: |
              🧐 **Guidelines:**

              - Search through [existing issues](https://github.com/sqlerrorthing/ShadowSniff/issues?q=is%3Aopen+is%3Aissue) first to ensure that this feature has not been requested before.
              - Write a descriptive title for your issue. Avoid generic or vague titles such as "Some suggestions" or "Ideas for improvement".
              - Keep your issue focused on one single problem. If you have multiple feature requests, please create separate issues for each of them.
              - Provide as much context as possible in the details section. Include screenshots, screen recordings, links, references, or anything else you may consider relevant.

    - type: textarea
      attributes:
          label: Describe your feature request.
          description: A clear and concise description of what the feature request is. Ex. I've always wanted [...]
      validations:
          required: true

    - type: textarea
      attributes:
          label: Additional context
          description: Add any other context or screenshots about the feature request here.
      validations:
          required: false

    - type: input
      attributes:
          label: Have you seen this feature elsewhere?
          description: If you've seen this idea implemented somewhere else (another stealer, etc.), mention where. Otherwise, leave blank.
          placeholder: "This feature is available in X and Z."

    - type: textarea
      attributes:
          label: How do you envision this feature being implemented?
          description: |
              Please describe how you think this idea could be implemented. Include all details you can — file paths, dependencies, or rough implementation steps.
              Describe the technical details or steps required to implement this feature, or leave blank if unsure.
          placeholder: "This is likely related to file located at X. We would need to steal Y and Z files. Supported extensions are A, B, C.."