[package]
name = "ftp"
version = "0.1.0"
edition = "2024"

[dependencies]
obfstr = "0.4.4"
tasks = { path = "../../tasks" }
utils = { path = "../../utils" }
windows = { version = "0.61.1", default-features = false, features = ["Data_Xml_Dom"] }
collector = { path = "../../collector" }