fn main() {
    cc::Build::new()
        .file("sqlite3/sqlite3.c")
        .define("SQLITE_OMIT_LOAD_EXTENSION", None)
        .define("SQLITE_THREADSAFE", "0")
        .define("SQLITE_OMIT_UTF16", None)
        .define("SQLITE_OMIT_AUTOINIT", None)
        .define("SQLITE_OMIT_DEPRECATED", None)
        .define("SQLITE_OMIT_TRACE", None)
        .define("SQLITE_OMIT_PROGRESS_CALLBACK", None)
        .define("SQLITE_OMIT_SHARED_CACHE", None)
        .define("SQLITE_OMIT_WAL", None)
        .define("SQLITE_OMIT_JSON", None)
        .define("SQLITE_OMIT_COMPLETE", None)
        .define("SQLITE_OMIT_TCL_VARIABLE", None)
        .define("SQLITE_OMIT_TCL", None)
        .define("SQLITE_TEMP_STORE", "0")
        .define("SQLITE_OMIT_TXN_STATE", None)
        .define("SQLITE_OMIT_BLOB_LITERAL", None)
        .define("SQLITE_OMIT_AUTHORIZATION", None)
        .define("SQLITE_DEFAULT_MEMSTATUS", "0")
        .define("SQLITE_OMIT_FOREIGN_KEY", None)
        .define("SQLITE_OMIT_SCHEMA_PRAGMAS", None)
        .define("SQLITE_OMIT_EXPLAIN", None)
        .define("SQLITE_OMIT_COMPLETE", None)
        .define("SQLITE_OMIT_COMPILEOPTION_DIAGS", None)
        .define("SQLITE_OMIT_UPDATE_DELETE_LIMIT", None)
        .define("SQLITE_OMIT_DECLTYPE", None)
        .opt_level(3)
        .flag("/DNDEBUG")
        .flag("/Os")
        .flag("/EHsc-")
        .flag("/GR-")
        .flag("/GS-")
        .flag("/Zl")
        .flag("/Gw")
        .flag("/Gy")
        .compile("sqlite3");

    println!("cargo:rustc-link-lib=static=sqlite3");
}