[package]
name = "browsers"
version = "0.1.0"
edition = "2024"

[dependencies]
tasks = { path = "../../tasks" }
utils = { path = "../../utils" }
database = { path = "../../database" }
obfstr = "0.4.4"
